import type { Question } from "@/lib/types"

export const aptitudeQuestions: Question[] = [
  {
    id: "apt-1",
    question: "If a train travels 360 km in 4 hours, what is its average speed in m/s?",
    options: ["25 m/s", "30 m/s", "20 m/s", "15 m/s"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "easy",
    explanation: "360 km / 4 hr = 90 km/hr. To convert to m/s: 90 * (5/18) = 25 m/s.",
  },
  {
    id: "apt-2",
    question: "What comes next in the sequence: 2, 6, 12, 20, 30, ?",
    options: ["40", "42", "36", "44"],
    correctAnswer: 1,
    topic: "Logic",
    difficulty: "easy",
    explanation: "Differences are 4, 6, 8, 10, 12. So the next number is 30 + 12 = 42.",
  },
  {
    id: "apt-3",
    question: "A bag contains 5 red, 3 blue, and 2 green balls. What is the probability of picking a blue ball?",
    options: ["0.3", "0.5", "0.2", "0.25"],
    correctAnswer: 0,
    topic: "Probability",
    difficulty: "easy",
    explanation: "Total balls = 10. P(blue) = 3/10 = 0.3.",
  },
  {
    id: "apt-4",
    question: "If APPLE is coded as 50, then MANGO is coded as?",
    options: ["57", "52", "59", "56"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "medium",
    explanation: "A=1,P=16,P=16,L=12,E=5 => 50. M=13,A=1,N=14,G=7,O=15 => 50. But using position sum: M(13)+A(1)+N(14)+G(7)+O(15) = 50. The codes match since sums are equal: 57 uses a different coding scheme where each letter = position + 1.",
  },
  {
    id: "apt-5",
    question: "Two pipes A and B can fill a tank in 12 and 18 hours respectively. If both pipes are opened, how long will it take to fill the tank?",
    options: ["7.2 hours", "8 hours", "6.5 hours", "9 hours"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "Rate of A = 1/12, Rate of B = 1/18. Combined = 1/12 + 1/18 = 5/36. Time = 36/5 = 7.2 hours.",
  },
  {
    id: "apt-6",
    question: "In a group of 100 people, 60 like tea, 45 like coffee, and 25 like both. How many like neither?",
    options: ["20", "15", "25", "30"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "easy",
    explanation: "Using inclusion-exclusion: 60 + 45 - 25 = 80 like at least one. So 100 - 80 = 20 like neither.",
  },
  {
    id: "apt-7",
    question: "A clock shows 3:15. What is the angle between the hour and minute hands?",
    options: ["7.5 degrees", "0 degrees", "15 degrees", "22.5 degrees"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "At 3:15, minute hand is at 90 degrees. Hour hand = (3*30) + (15*0.5) = 97.5 degrees. Angle = 97.5 - 90 = 7.5 degrees.",
  },
  {
    id: "apt-8",
    question: "If the ratio of boys to girls in a class is 3:5 and the total number of students is 40, how many girls are there?",
    options: ["25", "15", "20", "30"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "easy",
    explanation: "Girls = (5/8) * 40 = 25.",
  },
  {
    id: "apt-9",
    question: "Find the odd one out: 3, 5, 11, 14, 17, 21",
    options: ["14", "21", "3", "11"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "easy",
    explanation: "All numbers except 14 are odd. 14 is the only even number.",
  },
  {
    id: "apt-10",
    question: "A man walks 5 km North, then 3 km East, then 5 km South. How far is he from the starting point?",
    options: ["3 km", "5 km", "8 km", "13 km"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "easy",
    explanation: "North and South cancel out (5 - 5 = 0). He is 3 km East of the starting point.",
  },
  {
    id: "apt-11",
    question: "What is 15% of 15% of 15% of 1000?",
    options: ["3.375", "33.75", "0.3375", "337.5"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "15% of 1000 = 150. 15% of 150 = 22.5. 15% of 22.5 = 3.375.",
  },
  {
    id: "apt-12",
    question: "If the day before yesterday was Thursday, what day will it be the day after tomorrow?",
    options: ["Monday", "Tuesday", "Sunday", "Wednesday"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "easy",
    explanation: "Day before yesterday = Thursday, so today = Saturday. Day after tomorrow = Monday.",
  },
  {
    id: "apt-13",
    question: "A father is 3 times as old as his son. After 12 years, he will be twice as old. What is the son's current age?",
    options: ["12", "10", "15", "8"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "Let son's age = x. Father = 3x. After 12: 3x + 12 = 2(x + 12). 3x + 12 = 2x + 24. x = 12.",
  },
  {
    id: "apt-14",
    question: "How many times do the hands of a clock overlap in a 12-hour period?",
    options: ["11", "12", "10", "22"],
    correctAnswer: 0,
    topic: "Logic",
    difficulty: "medium",
    explanation: "The hands overlap 11 times in 12 hours (not at 12 o'clock separately because it's counted once).",
  },
  {
    id: "apt-15",
    question: "If you write all the numbers from 1 to 100, how many times does the digit 9 appear?",
    options: ["20", "19", "21", "18"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "9 appears in units place: 9,19,29,...,99 = 10 times. In tens place: 90-99 = 10 times. Total = 20.",
  },
  {
    id: "apt-16",
    question: "A shopkeeper gives two successive discounts of 10% and 20% on an item. What is the total discount percentage?",
    options: ["28%", "30%", "25%", "32%"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "medium",
    explanation: "Effective discount = 1 - (0.9 * 0.8) = 1 - 0.72 = 0.28 = 28%.",
  },
  {
    id: "apt-17",
    question: "Which word does NOT belong? Apple, Mango, Potato, Banana, Grape",
    options: ["Potato", "Apple", "Grape", "Banana"],
    correctAnswer: 0,
    topic: "Verbal",
    difficulty: "easy",
    explanation: "Potato is a vegetable. All others are fruits.",
  },
  {
    id: "apt-18",
    question: "Three dice are thrown simultaneously. What is the probability of getting a sum of 5?",
    options: ["1/36", "5/216", "1/72", "6/216"],
    correctAnswer: 3,
    topic: "Probability",
    difficulty: "hard",
    explanation: "Combinations giving sum 5: (1,1,3),(1,3,1),(3,1,1),(1,2,2),(2,1,2),(2,2,1) = 6 ways. Total outcomes = 216. P = 6/216.",
  },
  {
    id: "apt-19",
    question: "Complete the analogy: Book : Reading :: Fork : ?",
    options: ["Eating", "Writing", "Cooking", "Cutting"],
    correctAnswer: 0,
    topic: "Verbal",
    difficulty: "easy",
    explanation: "A book is used for reading. A fork is used for eating.",
  },
  {
    id: "apt-20",
    question: "If 6 workers can complete a job in 8 days, how many days will 4 workers take?",
    options: ["12 days", "10 days", "16 days", "14 days"],
    correctAnswer: 0,
    topic: "Math",
    difficulty: "easy",
    explanation: "Work = 6 * 8 = 48 worker-days. Days for 4 workers = 48/4 = 12 days.",
  },
]
